### ISSUE TITLE
when I run ntlmrelayx.exe ,something is wrong?

### ISSUE THREAD

**Issue by freeniuniu** [ropnop/impacket_static_binaries#8]
Impacket v0.9.17 - Copyright 2002-2018 Core Security Technologies

Traceback (most recent call last):
  File "ntlmrelayx.py", line 271, in <module>
  File "c:\users\admin\appdata\local\temp\pip-install-7erh71\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
  File "build\bdist.win32\egg\impacket\examples\ntlmrelayx\clients\__init__.py", line 79, in <module>
  File "site-packages\pkg_resources\__init__.py", line 1154, in resource_listdir
  File "site-packages\pkg_resources\__init__.py", line 1416, in resource_listdir
  File "site-packages\pkg_resources\__init__.py", line 1458, in _listdir
NotImplementedError: Can't perform this operation for unregistered loader type
[8872] Failed to execute script ntlmrelayx

**Comment by ropnop** [comment]
Hey! Yes, this is a known issue I call out in the README. The way the "relayx" scripts dynamically load modules makes them difficult to statically build and I never figured it out. I'm hoping someone can chime in with some suggestions or a PR cuz those would be killer to have statically compiled :)
