### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by Ak74-577** [ropnop/impacket_static_binaries#9]
C:\Tools>mssqlclient_windows.exe test/webadm:@192.168.151.131 -port 1433 -db master -windows-auth
Traceback (most recent call last):
  File "mssqlclient.py", line 25, in <module>
  File "C:\Python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 391, in load_module
    exec(bytecode, module.__dict__)
  File "impacket\version.py", line 11, in <module>
  File "site-packages\pkg_resources\__init__.py", line 535, in get_distribution
  File "site-packages\pkg_resources\__init__.py", line 415, in get_provider
  File "site-packages\pkg_resources\__init__.py", line 943, in require
  File "site-packages\pkg_resources\__init__.py", line 829, in resolve
pkg_resources.DistributionNotFound: The 'impacket' distribution was not found and is required by the application
[5204] Failed to execute script mssqlclient

**Comment by kildonan5** [comment]
Also seeing this same error running smbexec and ntlmrelayx (though i read after the fact that ntlmrelayx has its own issues) from Linux.

```
root@b284decbb1b3:/vt-cli# ./smbexec_linux_x86_64
Traceback (most recent call last):
  File "smbexec.py", line 44, in <module>
  File "/tmp/pip-install-sgiO4X/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "impacket/version.py", line 11, in <module>
  File "site-packages/pkg_resources/__init__.py", line 479, in get_distribution
  File "site-packages/pkg_resources/__init__.py", line 355, in get_provider
  File "site-packages/pkg_resources/__init__.py", line 898, in require
  File "site-packages/pkg_resources/__init__.py", line 784, in resolve
pkg_resources.DistributionNotFound: The 'impacket' distribution was not found and is required by the application
[49] Failed to execute script smbexec

```

**Comment by XingYun-Cloud** [comment]
C:\domain>getST.exe -dc-ip 192.168.137.100 -spn krbtgt/xy.local -impersonate Administrator xy.local/alex:du-a-123
Traceback (most recent call last):
  File "getST.py", line 51, in <module>
  File "C:\Python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 391, in load_module
  File "impacket\version.py", line 11, in <module>
  File "site-packages\pkg_resources\__init__.py", line 535, in get_distribution
  File "site-packages\pkg_resources\__init__.py", line 415, in get_provider
  File "site-packages\pkg_resources\__init__.py", line 943, in require
  File "site-packages\pkg_resources\__init__.py", line 829, in resolve
pkg_resources.DistributionNotFound: The 'impacket' distribution was not found and is required by the application
[2808] Failed to execute script getST

**Comment by hawaii67** [comment]
Same error here.........0.9.22.dev-binaries
